#!/bin/sh
# Shell script to read the output of parseout-feh and run vertex and pssect
#   to generate diagnostic plots for fit quality assessment.
# Written by G. Helffrich / ELSI (Titech)
#   Last update 2 Aug. 2024
OLD= APP=_
awk 'BEGIN{q="\""; nn=0}
{obj = $1; rest=$2; for(i=3;i<=NF;i++) rest = rest " " $(i)
   n = split(rest,v,","); delete TcB
   for(i=1;i<=n;i++) {
      m = split(v[i],f); ch = " "
      val = f[2]; for(j=3;j<=m;j++) {
         if (f[j] == "Tc" || f[j] == "B") {
            TcB[f[j]] = f[j+2]; j+=2
            continue
         }
         if (f[j] ~ /^[a-zA-Z][a-zA-Z0-9]*/ && j>3) ch = "\n"; else ch = " "
         val = val ch f[j]
      }
      if (TcB["B"] != "" || TcB["Tc"] != "") {
         val = val sprintf("\ntransition = 1 type = 8 Tc = %.0f B = %.1f p = 0.28", TcB["Tc"], TcB["B"])
      }
      if (f[1] == "FEH") FEH = val
      if (f[1] == "LIQ") LIQ = val
   }
   fn = sprintf("/tmp/pars%03d",nn++)
   printf "FEH=%s%s%s\n",q,FEH,q > fn
   printf "LIQ=%s%s%s\n",q,LIQ,q >> fn
   print obj,fn
   close(fn)
}' | while read obj fn ; do
#  echo "obj ${obj}; file ${fn}" | cat - ${fn}
   if [ "${OLD}" = "${obj}" ] ; then
      APP=$(($APP + 1))
      obj="${obj}_${APP}"
   else
      OLD="${obj}" APP=0
   fi
   . ${fn}                   # get property values
   cat << EOF >| MC_metal_mix.dat
 | comments are indicated by the | character. 
 | check for warnings at the end of the header section.

Metal Mix                                                                        |<= data base title

begin_standard_variables |<= name (<9 characters), reference value, tolerance
P(bar)      1.00   0.1E-3
T(K)      298.15   0.1E-4
Y(CO2)      0.00   0.1E-6
mu(C1)      0.00   0.1E-2
mu(C2)      0.00   0.1E-2
end_standard_variables

tolerance  -.1E-2  |<= DTOL for unconstrained minimization, energy units

begin_components |<= name (<5 characters), molar weight (g)
NA2O    61.9790
Mg      24.3045
AL2O3  101.9610
Si      28.0850
K2O     94.1960
CAO     56.0770
TIO2    79.8660
MNO     70.9370
Fe      55.8445
Cr      51.9960
NIO     74.6930
ZRO2   123.2200
CL2     70.9060
C       12.0110
H2       2.0155
O       15.9995
NACL    58.4427
end_components

begin_makes
end_makes 
                                                                                                                                            
th pdata produced at 16.35 on Wed 13 Feb,2002 (with sigma fit =  1.089)                                                                     
                                                                                                                                            
The Thermocalc data base includes data for ionic aqueous species, this data can be used in                                                  
Perple_X but was not included to conserve space. To create a data base containing                                                           
this data run the program HPTOVER and add the electron component.                                                                           
                                                                                                                                            
                                                            JADC Mar 9, 2002.                                                               
                                                                                                                                            
The Holland & Powell data base reproduced here has been augmented by shear moduli                                                           
with sources as specified in Connolly & Kerrick EPSL '02.                                                                                   
                                                                                                                                            
                                                            JADC Mar 9, 2004.                                                               
                                                                                                                                            
see comments in hp96ver.dat for additional information on changes from the                                                                  
earlier hp94ver.dat and hp90ver.dat files.                                                                                                  
                                                                                                                                            
comments can be written in the data file between entries, provided the first                                                                
character of comment card is left blank.                                                                                                    
                                                                                                                                            
WARNINGS: 1) The Holland & Powell thermodynamic data herein has been augmented                                                              
             by data for the Ghiorso et al. (2002, G3) pMELTS model. These data                                                             
             are not necessarily consistent and results obtained using the mixed                                                            
             data sources should be viewed with caution. The Ghirso et al data                                                              
             consists of the following melt (liquid) endmembers:                                                                            
                                                                                                                                            
               Name    Composition                                                                                                          
                                                                                                                                            
               qGL     Si4O8                                                                                                                
               coGL    Al4O6                                                                                                                
               faGL    Fe2SiO4                                                                                                              
               foGL    Mg2SiO4                                                                                                              
               woGL    Ca2Si2O6                                                                                                             
               nasGL   NaSi1/2O3/2                                                                                                          
               kalGL   KAlSiO4                                                                                                              
               h2oGL   H2O                                                                                                                  
                                                                                                                                            
Notation (not alphabetical!)                                                                                                                
                                                                                                                                            
Entity                     Symbol          Formula                                                                                          
                                                                                                                                            
akermanite                 ak              Ca2MgSi2O7                                                                                       
almandine                  alm             Fe3Al2Si3O12                                                                                     
andalusite                 and             Al2SiO5                                                                                          
andradite                  andr            Ca3Fe2Si3O12                                                                                     
clinohumite                chum            Mg9Si4O16(OH)2                                                                                   
clinozoisite               cz              Ca2Al3Si3O12(OH)                                                                                 
cordierite                 crd             Mg2Al4Si5O18                                                                                     
epidote(ordered)           ep              Ca2FeAl2Si3O12(OH)                                                                               
fayalite                   fa              Fe2SiO4                                                                                          
Fe-chloritoid              fctd            FeAl2SiO5(OH)2                                                                                   
Fe-cordierite              fcrd            Fe2Al4Si5O18                                                                                     
Fe-epidote                 fep             Ca2Fe2AlSi3O12(OH)                                                                               
Fe-osumilite               fosm            KFe2Al5Si10O30                                                                                   
Fe-staurolite              fst             Fe4Al18Si7.5O48H4                                                                                
forsterite                 fo              Mg2SiO4                                                                                          
gehlenite                  geh             Ca2Al2SiO7                                                                                       
grossular                  gr              Ca3Al2Si3O12                                                                                     
hydrouscordierite          hcrd            Mg2Al4Si5O18H2O                                                                                  
hydroxy-topaz              tpz             Al2SiO4(OH)2                                                                                     
kyanite                    ky              Al2SiO5                                                                                          
larnite-bredigite          larn            Ca2SiO4                                                                                          
lawsonite                  law             CaAl2Si2O7(OH)2H2O                                                                               
merwinite                  merw            Ca3MgSi2O8                                                                                       
Mg-chloritoid              mctd            MgAl2SiO5(OH)2                                                                                   
Mg-staurolite              mst             Mg4Al18Si7.5O48H4                                                                                
Mn-chloritoid              mnctd           MnAl2SiO5(OH)2                                                                                   
Mn-cordierite              mncrd           Mn2Al4Si5O18                                                                                     
Mn-staurolite              mnst            Mn4Al18Si7:5O48H4                                                                                
monticellite               mont            CaMgSiO4                                                                                         
osumilite(1)               osm1            KMg2Al5Si10O30                                                                                   
osumilite(2)               osm2            KMg3Al3Si11O30                                                                                   
phase A                    phA             Mg7Si2O8(OH)6                                                                                    
pumpellyite                pump            Ca4MgAl5Si6O21(OH)7                                                                              
pyrope                     py              Mg3Al2Si3O12                                                                                     
rankinite                  rnk             Ca3Si2O7                                                                                         
sillimanite                sill            Al2SiO5                                                                                          
spessartine                spss            Mn3Al2Si3O12                                                                                     
sphene                     sph             CaTiSiO5                                                                                         
spurrite                   spu             Ca5Si2O8(CO3)                                                                                    
tephroite                  teph            Mn2SiO4                                                                                          
tilleyite                  ty              Ca5Si2O7(CO3)2                                                                                   
vesuvianite                vsv             Ca19Mg2Al11Si18O69(OH)9                                                                          
zircon                     zrc             ZrSiO4                                                                                           
zoisite                    zo              Ca2Al3Si3O12(OH)                                                                                 
acmite                     acm             NaFeSi2O6                                                                                        
Ca-tschermaks pyroxene     cats            CaAl2SiO6                                                                                        
Diopside                   di              CaMgSi2O6                                                                                        
enstatite                  en              Mg2Si2O6                                                                                         
ferrosilite                fs              Fe2Si2O6                                                                                         
hedenbergite               hed             CaFeSi2O6                                                                                        
jadeite                    jd              NaAlSi2O6                                                                                        
mg-tschermak               mgts            MgAl2SiO6                                                                                        
pseudowollastonite         pswo            CaSiO3                                                                                           
pyroxmangite               pxmn            MnSiO3                                                                                           
rhodonite                  rhod            MnSiO3                                                                                           
wollastonite               wo              CaSiO3                                                                                           
anthophyllite              anth            Mg7Si8O22(OH)2                                                                                   
cummingtonite              cumm            Mg7Si8O22(OH)2                                                                                   
Fe-anthophyllite           fanth           Fe7Si8O22(OH)2                                                                                   
Fe-glaucophane             fgl             Na2Fe3Al2Si8O22(OH)2                                                                             
ferroactinolite            ftr             Ca2Fe5Si8O22(OH)2                                                                                
gedrite(Na-free)           ged             Mg5Al4Si6O22(OH)2                                                                                
glaucophane                gl              Na2Mg3Al2Si8O22(OH)2                                                                             
grunerite                  grun            Fe7Si8O22(OH)2                                                                                   
pargasite                  parg            NaCa2Mg4Al3Si6O22(OH)2                                                                           
riebeckite                 rieb            Na2Fe5Si8O22(OH)2                                                                                
tremolite                  tr              Ca2Mg5Si8O22(OH)2                                                                                
tschermakite               ts              Ca2Mg3Al4Si6O22(OH)2                                                                             
deerite                    deer            Fe18Si12O40(OH)10                                                                                
fe-carpholite              fcar            FeAl2Si2O6(OH)4                                                                                  
fe-sapphirine(793)         fspr            Fe3.5Al9Si1.5O20                                                                                 
mg-carpholite              mcar            MgAl2Si2O6(OH)4                                                                                  
sapphirine(442)            spr4            Mg4Al8Si2O20                                                                                     
sapphirine(793)            spr7            Mg3.5Al9Si1.5O20                                                                                 
annite                     ann             KFe3AlSi3O10(OH)2                                                                                
celadonite                 cel             KMgAlSi4O10(OH)2                                                                                 
eastonite                  east            KMg2Al3Si2O10(OH)2                                                                               
Fe-celadonite              fcel            KFeAlSi4O10(OH)2                                                                                 
margarite                  ma              CaAl4Si2O10(OH)2                                                                                 
Mn-biotite                 mnbi            KMn3AlSi3O10(OH)2                                                                                
muscovite                  mu              KAl3Si3O10(OH)2                                                                                  
Na-phlogopite              naph            NaMg3AlSi3O10(OH)2                                                                               
paragonite                 pa              NaAl3Si3O10(OH)2                                                                                 
phlogopite                 phl             KMg3AlSi3O10(OH)2                                                                                
Al-free chlorite           afchl           Mg6Si4O10(OH)8                                                                                   
amesite(14Ang)             ames            Mg4Al4Si2O10(OH)8                                                                                
clinochlore(ordered)       clin            Mg5Al2Si3O10(OH)8                                                                                
daphnite                   daph            Fe5Al2Si3O10(OH)8                                                                                
Fe-sudoite                 fsud            Fe2Al4Si3O10(OH)8                                                                                
Mn-chlorite                mnchl           Mn5Al2Si3O10(OH)8                                                                                
Sudoite                    sud             Mg2Al4Si3O10(OH)8                                                                                
antigorite                 atg             Mg48Si34O85(OH)62                                                                                
chrysotile                 chr             Mg3Si2O5(OH)2                                                                                    
Fe-talc                    fta             Fe3Si4O10(OH)2                                                                                   
Kaolinite                  kao             Al2Si2O5(OH)4                                                                                    
prehnite                   pre             Ca2Al2Si3O10(OH)2                                                                                
pyrophyllite               prl             Al2Si4O10(OH)2                                                                                   
talc                       ta              Mg3Si4O10(OH)2                                                                                   
tschermak-talc             tats            Mg2Al2Si3O10(OH)2                                                                                
albite                     ab              NaAlSi3O8                                                                                        
analcite                   anl             NaAlSi2O6H2O                                                                                     
anorthite                  an              CaAl2Si2O8                                                                                       
coesite                    coe             SiO2                                                                                             
cristobalite               crst            SiO2                                                                                             
heulandite                 heu             CaAl2Si7O186H2O                                                                                  
highalbite                 abh             NaAlSi3O8                                                                                        
kalsilite                  kals            KAlSiO4                                                                                          
laumontite                 lmt             CaAl2Si4O124H2O                                                                                  
leucite                    lc              KAlSi2O6                                                                                         
meionite                   me              Ca4Al6Si6O24(CO3)                                                                                
microcline                 mic             KAlSi3O8                                                                                         
nepheline                  ne              NaAlSiO4                                                                                         
quartz                     q               SiO2                                                                                             
sanidine                   san             KAlSi3O8                                                                                         
stilbite                   stlb            CaAl2Si7O187H2O                                                                                  
stishovite                 stv             SiO2                                                                                             
tridymite                  trd             SiO2                                                                                             
wairakite                  wrk             CaAl2Si4O12H2O3                                                                                  
baddeleyite                bdy             ZrO2                                                                                             
corundum                   cor             Al2O3                                                                                            
geikielite                 geik            MgTiO3                                                                                           
hematite                   hem             Fe2O3                                                                                            
hercynite                  herc            FeAl2O4                                                                                          
mgchromite                 mcrm            MgCr2O4                                                                                          
ilmenite                   ilm             FeTiO3                                                                                           
lime                       lime            CaO                                                                                              
magnesioferrite            mft             MgFe2O4                                                                                          
magnetite                  mt              Fe3O4                                                                                            
manganosite                mang            MnO                                                                                              
nickel                     oxide           NiO                                                                                              
periclase                  per             MgO                                                                                              
pyrophanite                pnt             MnTiO3                                                                                           
rutile                     ru              TiO2                                                                                             
spinel                     sp              MgAl2O4                                                                                          
ulvospinel                 usp             Fe2TiO4                                                                                          
brucite                    br              Mg(OH)2                                                                                          
diaspore                   dsp             AlO(OH)                                                                                          
goethite                   gth             FeO(OH)                                                                                          
ankerite                   ank             CaFe(CO3)2                                                                                       
aragonite                  arag            CaCO3                                                                                            
calcite                    cc              CaCO3                                                                                            
dolomite                   dol             CaMg(CO3)2                                                                                       
magnesite                  mag             MgCO3                                                                                            
rhodochrosite              rhc             MnCO3                                                                                            
siderite                   sid             FeCO3                                                                                            
diamond                    diam            C                                                                                                
graphite                   gph             C                                                                                                
iron                       iron            Fe                                                                                               
nickel                     Ni              Ni                                                                                               
carbon dioxide             CO2                                                                                                              
carbon monoxide            CO                                                                                                               
hydrogen                   H2                                                                                                               
methane                    CH4                                                                                                              
oxygen                     O2                                                                                                               
water fluid                H2O                                                                                                              
albite liquid              abL             NaAlSi3O8                                                                                        
anorthite liquid           anL             CaAl2Si2O8                                                                                       
diopside liquid            diL             CaMgSi2O6                                                                                        
enstatite liquid           enL             Mg2Si2O6                                                                                         
fayalite liquid            faL             Fe2SiO4                                                                                          
Fe-liquid (in KFMASH)      fliq            K3Fe0:5Al4Si19:5O47                                                                              
Forsterite liquid          foL             Mg2SiO4                                                                                          
H2O liquid                 h2oL            H2O                                                                                              
H2O liquid (in KFMASH)     hliq            H2O                                                                                              
K-feldspar liquid          kspL            KAlSi3O8                                                                                         
Mg liquid (in KFMASH)      mliq            K3Mg0:5Al4Si19:5O47                                                                              
Silica liquid              qL              SiO2                                                                                             
Sillimanite liquid         silL            Al2SiO5                                                                                          
H+(aq)                     H+                                                                                                               
Cl(aq)                     Cl-                                                                                                              
OH(aq)                     OH-                                                                                                              
Na+(aq)                    Na+                                                                                                              
K+(aq)                     K+                                                                                                               
Ca2+(aq)                   Ca++                                                                                                             
Mg2+(aq)                   Mg++                                                                                                             
Fe2+(aq)                   Fe++                                                                                                             
Al3+(aq)                   Al+++                                                                                                            
CO3--(aq)                  CO3                                                                                                              
Al(OH)3(aq)                AlOH3                                                                                                            
Al(OH)4----(aq)            AlOH4-                                                                                                           
KOH(aq)                    KOH                                                                                                              
HCl(aq)                    HCL                                                                                                              
KCl(aq)                    KCL                                                                                                              
NaCl(aq)                   NaCl                                                                                                             
CaCl(aq)                   CaCl2                                                                                                            
CaCl+(aq)                  CaCl+                                                                                                            
MgCl2(aq)                  MgCl2                                                                                                            
MgCl+(aq)                  MgCl                                                                                                             
FeCl(aq)                   FeCl2                                                                                                            
Aqueous silica             aqSi            SiO2                                                                                             
                                                                                                                                            
the following "end" card marks the end of the header section of the data file                                                               
                                                                                                                                            
end                                                                                                                                         
iron     EoS = 2  
Fe(1)
G0 = -11.9257 S0 = 27.32 V0 = .7092  
c1 = 46.2 c2 = .5158E-2 c3 = 723100 c5 = -556.2  
b1 = .746E-4 b5 = -.746E-3 b6 = 1680000 b7 = -252 b8 = 4  
end

H2O      EoS = 1  
H2(1)O(1)
G0 = -228542.3 S0 = 188.8  
c1 = 40.1 c2 = .8656001E-2 c3 = 487500 c5 = -251.2  
end

 
CO2      EoS = 102  
C(1)O(2)
G0 = -457224.7 S0 = 213.7  
c1 = 87.8 c2 = -.2644E-2 c3 = 706400 c5 = -998.9  
end

 
CO       EoS = 1  
C(1)O(1)
G0 = -137163.7 S0 = 197.67  
c1 = 45.7 c2 = -.97E-4 c3 = 662700 c5 = -414.7  
end

 
CH4      EoS = 1  
C(1)H2(2)
G0 = -50695.63 S0 = 186.26  
c1 = 150.1 c2 = .2062E-2 c3 = 3427700 c5 = -2650.4  
end

 
O2       EoS = 1  
O(2)
G0 = -61180.38 S0 = 205.2  
c1 = 48.3 c2 = -.691E-3 c3 = 499200 c5 = -420.7  
end

 
O2_fake  EoS = 1  
O(2)
G0 = -61180.38 S0 = 205.2  
c1 = 48.3 c2 = -.691E-3 c3 = 499200 c5 = -420.7  
end

 
H2       EoS = 1  
H2(1)
G0 = -.4549408E-2 S0 = 130.7  
c1 = 23.3 c2 = .4627E-2 c5 = 76.3  
end

iron-fcc EoS = 2  
Fe(1)
G0 = -357.7561 S0 = 27.321 V0 = .7075  
c1 = 198.8 c2 = -.4982E-1 c3 = -8939000 c4 = .1252E-4 c5 = -6986 c6 = 95970 c7 = 555300000  
b1 = -.3057E-3 b2 = .9504E-7 b3 = -.1789 b4 = 9.409 b5 = .1412E-1 b6 = 1330772 b8 = 5  
end

Fe_LIQ   EoS = 614  
Fe(1)
V0 = 0.70205                            | Fit (gmodel-fe.R)
b1 = 2.772e-5 b2 = 0 b6 = 148.0e4 b8 = -6.39 | Fit (gmodel-fe.R)
m0 = 1d-4
end

FCC-FeH        EoS = 648       | H in solid FeHx, NM; sol. model provides G
Fe(1)H2(1/2)
V0 = 0.8107344                 | ghcpfcc.R fit
b1 = 1.742e-5  b2 = 2.093e-8   | fit from Tagawa MGD volume
b6 = 162.55e4  b8 = -4.506     | K increment per mol of H
${FEH}
end

liq-FeH        EoS = 649       | H in liquid FeHx; sol. model provides G
Fe(1)H2(1/2)
b1 =  1.05555e-4  b2 = 0.0     | Tagawa data fit
${LIQ}
m0 = 1d-4
end
EOF
   cat << EOF >| MC_trial.dat
MC_metal_mix.dat     thermodynamic data file                                                                                                   
no_print | print generates print output
plot     | no_plot suppresses plot output
         | solution_model.dat     solution model file, blank = none                                                                                                                                                                                                        
FeH melting (Tagawa et al. 2022, obj ${obj})
perplex_option.dat |feh_popts.dat     computational option file                                                                                                                                                                                                                     
    5 calculation type: 0 - composition, 1 - Schreinemakers, 3 - Mixed, 4 - gwash, 5 - gridded min, 7 - 1d fract, 8 - gwash 9 - 2d fract, 10 - 7 w/file input
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 number component transformations
   16 number of components in the data base
    0 component amounts, 0 - molar, 1 weight
    0 unused place holder, post 06
    0 unused place holder, post 06
    0 unused place holder, post 05
    0 ifug EoS for saturated phase
    2 gridded minimization dimension (1 or 2)
    0 special dependencies: 0 - P and T independent, 1 - P(T), 2 - T(P)
 0.00000      0.00000      0.00000      0.00000      0.00000     Geothermal gradient polynomial coeffs.

begin thermodynamic component list
Fe    1  1.00000      0.00000      0.00000     molar  amount
H2    1  0.50000      0.00000      0.00000     molar  amount
end thermodynamic component list


begin saturated component list
end saturated component list


begin saturated phase component list
end saturated phase component list


begin independent potential/fugacity/activity list
end independent potential list


begin excluded phase list
H2
iron
FeA1
FeA2
FeA3
Fe_LIQ
Fe(l)
Feliq
Fe(g)
end excluded phase list


begin solution phase list
end solution phase list

200e4        5300.0     0.00000000  0.0000      0.0000     max p, t, xco2, u1, u2
 1.          300.00     0.00000000  0.0000      0.0000     min p, t, xco2, u1, u2
 0.0000      0.0000     0.00000000  0.0000      0.0000     unused place holder post 06

 1  2  4  5  3   indices of 1st & 2nd independent & sectioning variables
EOF
################################################################################
   (echo MC_trial; echo n) | ../src/vertex
   (echo MC_trial; echo n; echo feh-meltingdata.dat) | ../src/pssect
   cp -f MC_trial.ps /tmp/MC_feh_${obj}.ps
   rm ${fn}
done
